Preserve data
mahammad-mostafa/school-library pull request #6
Opened 2023-10-25 14:34 UTC by mahammad-mostafa

- Module `Storage` used for handling JSON files read & write
- Module `Storage` includes two methods (`read_file` / `write_file`)
- Implemented serializing & deserializing for object instances using (`generate_string` / `parse_string`)
- All data is preserved inside three files (`books.json` / `people.json` / `rentals.json`)

2023-10-25 14:44 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi Team! @mahammad-mostafa @alexansaa @stino-x, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜  
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 14:44 UTC, anagudelogu commented on book_class.rb
> +require 'JSON'
- [ ] You did a great job working on this milestone! 💯 However, I'm getting the following error:

![image](https://github.com/mahammad-mostafa/school-library/assets/77069011/e1144093-5ac1-4665-a6ef-29b5a20fbcca)

Once I changed it to lowercase `json` it worked fine! 🤓 🔧

2023-10-25 14:44 UTC, anagudelogu commented on storage_module.rb
> +require 'JSON'
- [ ] Here happens the same:

![image](https://github.com/mahammad-mostafa/school-library/assets/77069011/00cfd2e3-b478-400f-83a7-19159d2e955c)

Please consider changing it to lowercase! 🤓 🔧

2023-10-25 14:58 UTC, shahadat3669 approved these changes
Hi everyone, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ On exit from  app save all the data
✅ One per type of data are storing and named accordingly (e.g. rentals.json)
✅ On startup of the app load all data from files

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-25 15:01 UTC, merged

2023-10-26 23:24 UTC, nicupop729 commented
@anagudelogu & @shahadat3669  please note that co-authored commits are not acceptable to have while building projects at Micorverse.

Co-authored commits are done by a student who is adding the names and GitHub accounts of the other students while creating the name of the commits.

We cannot accept this activity as done in pair programming, as we cannot get the level of implication for all group members.

If you encounter this type of situation in the future, let's please invalidate the CRR.

Thank you!